### ISSUE TITLE
YJN: Issues: Research Plan: Create

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/YouthJusticeNav#110]
### Overview
We need issues in the prioritized backlog, to create research plans for all the work we have already defined per plan, so that when new researchers join the team, they have work ready to do

### Action Items
- #76 
  - [x] Create research plan issue #108 
- #77
  - [X] Create research plan issue #111 
- #78 
  - [x] Create research plan issue #109 
- #79
  - [x] Create research plan issue #113 
- #80 
  - [X] Create research plan issue #114 
- #81 
  - [X] Create research plan issue #116 
- #82
  - [X] Create research plan issue #115 
- #96 
  - [X] Create research plan issue #117 

### Resources/Instructions
- [Research Plan Issue Template](https://github.com/hackforla/YouthJusticeNav/issues/new?assignees=&labels=feature%3A+missing%2C+feature%3A+research+plan%2C+Role%3A+UI%2FUX+research%2C+size%3A+1pt&template=research--research-plan.md&title=TWE%3A+Create+Research+Plan+for+RP%5B%23%23%23%5D)
- [Research Output Overview](https://github.com/hackforla/YouthJusticeNav/wiki/Research-Output-Overview)
- [YJN: Template: Internal Research Plan](https://docs.google.com/document/d/1MRSKJcnA-PViABDzPtPIdYBslwvG70uwAAZKNggh8sU/template/preview)

**Comment by Rabia2219** [comment]
@ltung05 
Hi Leroy,
I've added RP008 to the list...please make the issue for that...
Also...please review all the issues that you've created and replace TWE with YJN where applicable...thanks...

**Comment by ExperimentsInHonesty** [comment]
This issue has been completed.  We have an epic for each research plan and the research plan issues have also been made.  The rest of the epic issues that need to be made per research plan, can't be made until we have the template done.
