### ISSUE TITLE
YJN: PM Meeting Agenda

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/YouthJusticeNav#112]
### Overview
This issue tracks the agenda for the PM meetings for the Youth Justice Navigator Project

### Action Items
- [ ] Copy the template to a comment below
- [ ] Add date
- [ ] Fill out template

#### Template
```
## [DATE] Agenda and Notes

### Prework
- [ ] Issue for audit
- [ ] Check to see if there are questions, and if yes, add it to agenda

### Roll Call
- [ ] Bonnie
- [ ] Rabia
- [ ] Leroy

#### Recurring items: Happens on the PM Monday meeting
 - [ ] Review any issues that are in the [new issue approval column]()
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bonnie]
       - [ ] [Rabia]
       - [ ] [Leroy]
- [ ] Finish adding labels to the issue that are still missing them (see audit links above)
- [ ] Review issues with [epic label]()
- [ ] Review the #59  and make it ready for the next team meeting
- [ ] Review the #70 and add agenda items

### Items Carried Forward
- [ ] 
### New Items
- [ ] 
- [ ] Carry forward the "New Items" that we did not get to look at today
  
### FYIs

### Notes from meeting
- 

### Task Items carried forward from last meeting

### New Task Items
If they are issues to be made, add them here  #85  otherwise add them below this line as checkboxes
- [ ] 

#### Items for next week's agenda
- [ ] 


```
### Resources/Instructions

- #70
- #59 
- [YJN: Info architecture draft](https://sites.google.com/d/1WXPOrvNHCfQW6juwn4uBNeMaSQw_bNj2/p/1_G3dZpjLhN4AZjA-IOMfIUWSxymPrV4U/edit)
- [Copy of YJN: Info architecture draft](https://sites.google.com/d/1gPgl3Cz2259XXDjhV3z2BrqjPaVZtBQE/p/1S078_7Fql8VYU3Wvxv6FlxmA8qHYBOhE/edit)

### Agendas by date
[2022-10-07](https://github.com/hackforla/YouthJusticeNav/issues/112#issuecomment-1272108308)
[2022-11-03](https://github.com/hackforla/YouthJusticeNav/issues/112#issuecomment-1302175044)

**Comment by Rabia2219** [comment]
Hyun Joo Sandy Oh:
Prior to graduate school, I was a researcher at a private school in Seoul (15,000 students). I was in charge of rolling out a digital learning platform at lightning speed. I worked with engineers, writers, editors, and the admin, including the CEO. I left that job to pursue my PhD in Cultural Anthroplogy. Skillset: ethnography, interviews, focus groups, shadowing, diary studies. My knowledge was always premised in my studies as a sociologist and political scientist, which were more quant focused, during my undergrad. After finishing my PhD, I also worked as a researcher in the writer’s room for Godfather of Harlem, starring Forrest Whitaker. I advised the showrunner, exec producers, writers and actors on needed research flow, script development, etc. I now work at UC Irvine. I’ve been conducting my own research on the intersections of DEI issues and tech.
Hyun Joo Sandy Oh:

LinkedIn: https://www.linkedin.com/in/sandyoh/

**Comment by Rabia2219** [comment]
## 2022-10-07 Agenda and Notes

### Prework
- [ ] Issue for audit
- [ ] Check to see if there are questions, and if yes, add it to agenda

### Roll Call
- [x] Bonnie
- [x] Rabia
- [x] Leroy

#### Recurring items: Happens on the PM meeting
 - [ ] Review any issues that are in the [new issue approval column]()
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bonnie]
       - [ ] [Rabia]
       - [ ] [Leroy]
- [ ] Finish adding labels to the issue that are still missing them (see audit links above)
- [ ] Review issues with [epic label]()
- [ ] Review the #59  and make it ready for the next team meeting

### Items Carried Forward
- [ ] 
### New Items
- [ ] Review [new SoW](https://docs.google.com/document/d/1D3ITnB0HJ4co0WLJpK5xKnW8n2NiXJxiL3m_9LYPfrQ/edit?usp=sharing) for PM
- [x] Review [Hyun Joo's bio](https://github.com/hackforla/YouthJusticeNav/issues/112#issuecomment-1264643856) (UX researcher interested in joining YJN)
    - [x]  invite her speak at the UI/UX CoP
    - [x] invite her to join
- [x] Reach out to [Royston G King](https://hackforla.slack.com/archives/C01Q24YF56J/p1665064200648579)
- [ ] Review and update [open role posting](https://github.com/hackforla/UI-UX/projects/2#card-75701803) for UX research team lead
- [ ] Review with Leroy
   - [ ] #110
   - [ ] PM Meeting agenda template
     - [ ] Adding links
     - [ ] Using it to prepare agendas each week
     - [ ] [Label audit issue](https://github.com/hackforla/internship/issues/93) from TWE
     - [ ] [Team Questions issue](https://github.com/hackforla/internship/issues/59) from TWE
    - [ ] All team meeting agenda from TWE
- [ ] Carry forward the "New Items" that we did not get to look at today
  
### FYIs

### Notes from meeting
- Bonnie will reach out to Royston
- Leroy will work on customizing the How to Write a Research Plan for YJN
- Megan needs to add questions to the RP001 Research Plan

### Task Items carried forward from last meeting

### New Task Items
If they are issues to be made, add them here  #85  otherwise add them below this line as checkboxes
- [ ] 

#### Items for next week's agenda
- [ ]

**Comment by Rabia2219** [comment]
Add to stakeholder meeting:

- Karen's email: Interns should go through the videos
- Drive audit spreadsheet: review
- Hyun's request to join
- Reach out to Royston G King
- Bonnie's supervision of Roger and the youth

Discuss with Bonnie:
- Rabia's hours: 31 remaining as of 2022-10-13

**Comment by ltung05** [comment]
#118 and #119 are completed

**Comment by Rabia2219** [comment]
## 2022-11-03

#### Agenda Items
Review:
- [YJN: PM Scope of Work: Extended](https://docs.google.com/document/d/1D3ITnB0HJ4co0WLJpK5xKnW8n2NiXJxiL3m_9LYPfrQ/edit)
- [YJN: Project Scope of Work: PM 1 Year](https://docs.google.com/document/d/1Pz-OU6cdxtaytTtLdnZ62blcCPhoQxt6hLmmDn3Wj88/edit#)
- [YJN: PM: Collabathon Roadmap](https://docs.google.com/document/d/1GPr-LWsj9tuHUc9iAnGhA9cusz-w3RXCKLu0RIaiq4k/edit#heading=h.u0hcc3g5nrs3)
- [YJN: PM: Website Development Roadmap](https://docs.google.com/document/d/1HGIGGTJwlW5wyZjT5gAu2-3M00DbHk3Ce5qg5Kh2ZH4/edit#heading=h.u0hcc3g5nrs3)
- [YJN: PM: Volunteer/Vendor Engagement Roadmap](https://docs.google.com/document/d/1X7vHuqA3VLR41ov9e14sTGw7dvRpFz38ZPdsFV3eKfg/edit#heading=h.u0hcc3g5nrs3)

#### Resources
- [YJN: PM Project Scope of Work: PM 30 days](https://docs.google.com/document/d/1og7pqjeD9XH3thTYtmdqCxDfukUfzYGoIoJRFVQPhD8/edit#heading=h.3wyh7eycww6h)
- [CTS: YJN: Funding budgets](https://docs.google.com/spreadsheets/d/1Fc9d3_Cxeo8BG_GEyxB_pdvrSVVgU1C5VLIz6ErRYCQ/edit#gid=457932426)
- [YJN Timeline/Milestones](https://docs.google.com/spreadsheets/d/1YZ9tmzNmdTg8B7AXDpMlQpCA3aEdAHQU3-zUL5CirTk/edit#gid=0) - WIP

#### Notes
- Add these granular requirements to internal document for Collabathon Kit Creation:
Requirements:
  - GitHub
  - Zoom
  - Figma
  - Slack
  - Gmail (for accessing google drive)
 - Add creation of researcher training deck to research prep
 - Possibly set up a committee for post Collabathon analysis
- Examples from BOP 
   - [BOP Processes and Practices Data
](https://docs.google.com/spreadsheets/d/1N0VSDhYyy5WhX_z18Q0RvLlGO29JGGdMxVsD4X3nFYs/edit#gid=186025086)
   - [BOP Processes and Practices Data [INTERNAL]
](https://docs.google.com/spreadsheets/d/1ZyeIDeHnzwjnkfYuhzeUZQo5tYXpbdnF-HKqN8cZy_A/edit#gid=0)
- Look up youth bios
- Create personas to see if the youth match all or we need to recruit more youth
- Possible requirement for submitting prototype at the Collabathon: prepare a final slide deck and presentation with the following:
   - Concept
   - What legal section it addresses
   - Presentation of idea: wireframes, screenshots, video scripts, storyboards
   - Next Steps
- [Storyboard Template](https://docs.google.com/presentation/d/1BQri-6aYkUFpJoNlMqUheZ6ek2f_pyqGD34iqLWhY6k/edit#slide=id.p7)

**Comment by ExperimentsInHonesty** [comment]
Requirements

- GitHub
- Zoom
- Figma
- Slack
- Gmail (for accessing google drive)

**Comment by Rabia2219** [comment]
## 2022-11-11

#### Agenda Items
Review:
- [YJN: PM Scope of Work: Extended](https://docs.google.com/document/d/1D3ITnB0HJ4co0WLJpK5xKnW8n2NiXJxiL3m_9LYPfrQ/edit)
- [YJN: Project Scope of Work: PM 1 Year](https://docs.google.com/document/d/1Pz-OU6cdxtaytTtLdnZ62blcCPhoQxt6hLmmDn3Wj88/edit#)
- [YJN: PM: Collabathon Roadmap](https://docs.google.com/document/d/1GPr-LWsj9tuHUc9iAnGhA9cusz-w3RXCKLu0RIaiq4k/edit#heading=h.u0hcc3g5nrs3)
- [YJN: PM: Website Development Roadmap](https://docs.google.com/document/d/1HGIGGTJwlW5wyZjT5gAu2-3M00DbHk3Ce5qg5Kh2ZH4/edit#heading=h.u0hcc3g5nrs3)
- [YJN: PM: Volunteer/Vendor Engagement Roadmap](https://docs.google.com/document/d/1X7vHuqA3VLR41ov9e14sTGw7dvRpFz38ZPdsFV3eKfg/edit#heading=h.u0hcc3g5nrs3)

#### Resources
- [YJN: PM Project Scope of Work: PM 30 days](https://docs.google.com/document/d/1og7pqjeD9XH3thTYtmdqCxDfukUfzYGoIoJRFVQPhD8/edit#heading=h.3wyh7eycww6h)
- [CTS: YJN: Funding budgets](https://docs.google.com/spreadsheets/d/1Fc9d3_Cxeo8BG_GEyxB_pdvrSVVgU1C5VLIz6ErRYCQ/edit#gid=457932426)
- [YJN Timeline/Milestones](https://docs.google.com/spreadsheets/d/1YZ9tmzNmdTg8B7AXDpMlQpCA3aEdAHQU3-zUL5CirTk/edit#gid=0) - WIP

**Comment by ltung05** [comment]
- #122 created

**Comment by ExperimentsInHonesty** [comment]
## 2023-02-03 Agenda and Notes

### Prework
- [ ] Issue for audit
- [ ] Check to see if there are questions, and if yes, add it to agenda

### Roll Call
- [ ] Bonnie
- [ ] Leroy

#### Recurring items: Happens on the PM Monday meeting
 - [ ] Review any issues that are in the [new issue approval column]()
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bonnie]
       - [ ] [Rabia]
       - [ ] [Leroy]
- [ ] Finish adding labels to the issue that are still missing them (see audit links above)
- [ ] Review issues with [epic label]()
- [ ] Review the #59  and make it ready for the next team meeting
- [ ] Review the #70 and add agenda items

### Items Carried Forward
- [ ] 
### New Items
- [ ] 
- [ ] Carry forward the "New Items" that we did not get to look at today
  
### FYIs

### Notes from meeting
- 

### Task Items carried forward from last meeting

### New Task Items
If they are issues to be made, add them here  #85  otherwise add them below this line as checkboxes
- [ ] 

#### Items for next week's agenda
- [ ]

**Comment by Rabia2219** [comment]
@Rabia2219 test
