### ISSUE TITLE
Team Meeting Agenda

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/YouthJusticeNav#59]
### Overview
We are using this issue to track meeting agenda for HfLA internal team meetings

### Action Items
Update agenda items every week as a comment

**Comment by Olivia-Chiong** [comment]
Week of 9/20/2021 

Agenda Items
- Review documents shared by Doreen
- Review logo usability hub
- Come up with roadmap plan for next 6 months

**Comment by ExperimentsInHonesty** [comment]
The team does not currently have a running agenda for the team meeting

**Comment by ExperimentsInHonesty** [comment]
@Olivia-Chiong Please add to next team meeting or an issue 
- [ ] Update open role posting
   - [ ] Add YJN log from hackforla.org website to https://github.com/hackforla/UI-UX/projects/2#card-75701824 (not the logo blue logo).
   - [ ] Add between Project Name and Volunteer Opportunity
     - **About the Project**: [your brief description replaces these brackets]

**Comment by ExperimentsInHonesty** [comment]
Please add this to this week's agenda and get it done during the meeting
- [ ] Taking a picture of the team [CTA Instructions](https://docs.google.com/presentation/d/1UDHwTQ1C3y01CiNS0mvPjNBHJFlm2Txs/preview)

**Comment by Rabia2219** [comment]
2022-04-26
- Have Wendy give an update on the FigJam setup
- Have Wendy create a new issue

**Comment by Rabia2219** [comment]
2022-05-03

- clean up FigJam file
- update the instructions accordingly
- setup am email for just the stakeholders
- Wendy's presentation

**Comment by wendytran1** [comment]
- [ ] Wendy to be updated on last Friday's meeting

**Comment by Rabia2219** [comment]
2022-05-06
- Have Chali work on the on the communication assets
- https://docs.google.com/presentation/d/1ePZ5qL9aMndKq2T6SBPVLGaTf1bHzkNvkv50_CL4IoQ/edit

**Comment by Rabia2219** [comment]
2022-05-17

- If Wendy attends, have her present her FigJam session
- If Chali attends, update her on the image requirements for the [Presentation Template](https://docs.google.com/presentation/d/1ePZ5qL9aMndKq2T6SBPVLGaTf1bHzkNvkv50_CL4IoQ/edit#slide=id.gfaa841ff41_0_8)
- Brainstorm on creating a meeting agenda
  - Example: [Internship Meeting Agendas](https://github.com/hackforla/internship/issues)

**Comment by Rabia2219** [comment]
### Date: 2022-05-20

### Roll Call:

- [ ] Bonnie
- [ ] Rabia
- [ ] Leroy
- [ ] Wendy
- [ ] Chali

### New Items:
- [ ] Wendy will provide an update on her assignment
- [ ] Two people (one UX and the other is unknown) are interested in joining the team. We need to decide which meeting to invite them to.
- [ ] Check on update on #27 from Chali

### Notes:

**Comment by Rabia2219** [comment]
### Date: 2022-05-24

### Roll Call

- [ ] Bonnie
- [ ] Rabia
- [ ] Leroy
- [ ] Wendy
- [ ] Chali
- [ ] Megan
- [ ] Taylor

### Items Carried Forward
- [ ] Setup email for stakeholders

### New Items
- [ ] Introductions for Megan and Taylor
- [ ] Overview of where the project stands
- [ ] What we need from the UX research side
- [ ] Wendy can give an overview of the 6-3-5 FigJam session
- [ ] Rabia can give an overview of the Collabathon ideas FigJam

### Notes

**Comment by Rabia2219** [comment]
### Date: 2022-05-30

### Roll Call

- [ ] Bonnie
- [ ] Rabia
- [ ] Leroy
- [ ] Wendy
- [ ] Chali
- [ ] Megan
- [ ] Taylor

### New Items
- [ ] Introductions for Megan and Taylor
- [ ] Overview of where the project stands
- [ ] What we need from the UX research side
- [ ] Setup a recurring check-in meeting for Bonnie and Rabia
- [ ] Setup email for stakeholders

### Notes

**Comment by Rabia2219** [comment]
### Date: 2022-05-30

### Roll Call

- [x] Bonnie
- [x] Rabia
- [ ] Leroy
- [ ] Wendy
- [ ] Chali
- [x] Megan
- [x] Taylor

### Agenda
- [ ] Finish onboarding #71 
   - [ ] Wendy
   - [ ] Megan
   - [ ] Taylor
- [ ] Create new issue for/with Megan and Taylor
- [ ] Wendy's update on #69
- [ ] Chali's update on #27
- [ ] Setup a recurring check-in meeting for Bonnie and Rabia
- [ ] Setup email for stakeholders

### Notes

### Tasks

- [ ]

**Comment by Rabia2219** [comment]
- Olivia shared the drive with the documents related to the 7 areas with us:
> - Final means ready for site
> - PD means reviewed by legal department
> - Youth reviewing means being reviewed by youth

**Comment by Rabia2219** [comment]
### Date: 2022-06-06

### Roll Call

- [ ] Bonnie
- [ ] Rabia
- [ ] Leroy
- [ ] Wendy
- [ ] Chali
- [ ] Megan
- [ ] Taylor

### New Agenda Items

- [ ] Reply to Alicia's email
- [ ] Draft the paragraph she has asked for
- [ ] Create agenda for stakeholder meeting on 2022-06-10 #70 

### Items Carried Forward

- [ ] Finish onboarding #71 
   - [ ] Wendy
   - [ ] Megan
   - [ ] Taylor
- [ ] Chali's update on #27
- [ ] Setup a recurring check-in meeting for Bonnie and Rabia
- [ ] Setup email for stakeholders
- [ ] Add members to project page on HfLA website
   - YJN issue #57 
   - [Internship issue](https://github.com/hackforla/internship/issues/136) on adding members

### Notes

### Tasks

- [ ]

**Comment by Rabia2219** [comment]
2022-07-11

Research Goals:
- focus groups (2)
  - qualifier: must have attended a hackathon 
- applications process
- polls at the end of activities
- end of day surveys
- end of week reflective surveys
-  Collabathon Goals
   - what they are
     - share with shareholders to see if they are on the same page
   - did we achieve the collabathon goals

**Comment by Rabia2219** [comment]
### Date: 2022-08-08

### Roll Call

- [ ] Bonnie
- [ ] Rabia
- [ ] Megan
- [ ] Taylor
- [ ] Leroy
- [ ] Wendy
- [ ] Chali

### New Agenda Items

- [ ]

### Items Carried Forward

- [ ]

### Notes

-

### Tasks items from meeting
- [ ]

**Comment by Rabia2219** [comment]
### Date: 2022-08-22

### Roll Call

- [ ] Bonnie
- [x] Rabia
- [x] Megan
- [x] Taylor


### New Agenda Items

- [ ] Feedback from Taylor and Megan on the research templates
- [ ] Assignment of new tasks

### Items Carried Forward

- [ ]

### Notes
 - Will confirm with Bonnie whether they should start working on RP001
 - Will confirm with Bonnie if the researchers can take over the issue template and template document creation

### Tasks items from meeting
- [ ]

**Comment by Rabia2219** [comment]
### Date: 2022-09-12

### Roll Call

- [ ] Bonnie
- [x] Rabia
- [x] Megan
- [x] Taylor


### New Agenda Items

- [ ] Feedback on #94 and #95 

### Items Carried Forward

- [ ]

### Notes
- 

### Tasks items from meeting
- [ ]

**Comment by Rabia2219** [comment]
### Date: 2022-10-03

### Roll Call

- [x] Bonnie
- [x] Rabia
- [x] Megan
- [x] Taylor
- [x] Leroy


### New Agenda Items
- [x] Review #108 and  #109 


### Items Carried Forward

- [ ]

### Notes


### Tasks items from meeting
- [ ]

**Comment by ltung05** [comment]
### Date: 2022-10-17

### Roll Call

- [x] Bonnie
- [x] Rabia
- [x] Megan
- [x] Taylor
- [x] Leroy
- [x] Sandy

### New Agenda Items
- [x] Introductions and project overview with Sandy
- [ ] Onboard Sandy (use #71)
- [x] Review Research Plans
   - [x]  #108 - Megan added the questions
   - [x] #113 
   - [x] #114 
- [x] Review #118 

### Items Carried Forward
- [ ]

### Notes
- The questions for During Event Surveys need to be more modular
- The questions for End of Day Surveys need to be drafted around whether the number of activities/speakers was helpful or relevant, too much or just right, etc

### Tasks items from meeting
- [ ]

**Comment by ExperimentsInHonesty** [comment]
### Date: 2022-10-21

### Roll Call

- [x] Bonnie
- [x] Rabia
- [ ] Megan
- [ ] Taylor
- [x] Leroy
- [x] Sandy

### New Agenda Items
- [x] Updates/questions from Sandy
- [x] Add Royston to slack channel?
- [x] New UX Research interest
  - [x] [tizheng](https://github.com/hackforla/YouthJusticeNav/issues/59#issuecomment-1287524250)
  - [x] [Ayah](https://github.com/hackforla/YouthJusticeNav/issues/59#issuecomment-1287524500)
- [x] Review and update [open role posting](https://github.com/hackforla/UI-UX/projects/2#card-75701803) for UX research team lead
- [x] Review #118
- [ ] Review with Leroy
   - [ ] [PM Meeting agenda template](https://github.com/hackforla/YouthJusticeNav/issues/112#issue-1391654359)
      - [ ] Adding links
      - [ ] Using it to prepare agendas each week
   - [ ] [Label audit issue](https://github.com/hackforla/internship/issues/93) from TWE
   - [ ] [Team Questions issue](https://github.com/hackforla/internship/issues/59) from TWE
   - [ ] [All team meeting agenda from TWE](https://github.com/hackforla/internship/issues/101#issue-1088668388)
- [x] We need to write a follow up email to Karen



### Items Carried Forward
- [ ]

### Notes
- Leroy will update the role posting for UX
- Leroy will create a new role posting for PM
- Bonnie and I will meet on Monday to work on Karen's follow up email
- Will reach out the interested UX researchers

### Tasks items from meeting
- [ ]

**Comment by Rabia2219** [comment]
tizheng
  [9:58 PM](https://hackforla.slack.com/archives/C01J94D6GAC/p1666148325071729)
Hello! My name is Ting. Are you all in need of any UX researchers for your team? I just attended the new joiner orientation. I saw in GitHub you had posted about needing a UX research team lead? I´d love to be involved if so. Thanks!
tizheng
  [4:02 PM](https://hackforla.slack.com/archives/D047N61FRLH/p1666213343148749)
Hi Rabia, I am interested in the Ux researcher position. Could you share more information with me?

**Comment by Rabia2219** [comment]
Ayah Abo-Basha (she/her)
  [8:05 PM](https://hackforla.slack.com/archives/D047A8BCX99/p1666227909361589)
Hi Rabia!
This is Ayah, an anthropologist and emerging UX Researcher who just joined HfLA during last week’s onboarding session. As a former Criminal Justice Lead Researcher with ACLU’s sister org in Egypt, I’m extremely interested in the Youth Justice Nav project. I noticed the project had an opening for a UX Research role and would love to attend a meeting to see if there might be alignment to work together?
Thanks and hope your week is going well!
Ayah

**Comment by Rabia2219** [comment]
### Date: 2022-10-24

### Roll Call
- [x] Bonnie
- [x] Rabia
- [ ] Megan
- [x] Taylor
- [x] Leroy
- [x] Sandy

### New Agenda Items
- [x] Quick 'hellos' for Ayah and Ting who will be observing today
- [x] Updates from Sandy
- [ ] Review
   - [x] #113 
   - [ ] #114   

### Items Carried Forward
- [ ]

### Notes
- Sandy needs to be assigned to an issue ASAP
- Add a QR code with a link to the packets where applicable
- There will be a during Collabathon website section to direct the participants to relevant links

### Tasks items from meeting
- [ ] Create a new issue: FigJam information booth to use during the Collabathon

**Comment by Rabia2219** [comment]
### Date: 2022-10-31

### Roll Call
- [x] Bonnie
- [x] Rabia
- [x] Megan
- [x] Taylor
- [ ] Leroy
- [x] Sandy

### FYIs
- Ayah has decided to join another project
- Haven't heard back from Ting

### New Agenda Items
- [ ] Research Review
   - [ ] Sandy's #111
   - [ ] Taylor's #113 
   - [ ] Megan's #114 
- [ ] PM review
   - [ ] #118
   - [ ] #119  

### Items Carried Forward
- [ ]

### Notes
- Youth under 18
  -  will not be included in the Collabathon mainly due to consent issues
  - As for the Focus Groups, they could come as SMEs
  - Provide training for them to answer questions
  - provide questions to a group and ask who would like to answer
  - 

### Tasks items from meeting

**Comment by Rabia2219** [comment]
### Date: 2022-11-07

### Roll Call
- [x] Bonnie
- [x] Rabia
- [x] Megan
- [x] Taylor
- [x] Leroy
- [x] Sandy

### New Agenda Items
- [x] Quick 'hellos' for UX researchers who will be observing today
- [ ] Review
   - [ ] #113 
   - [ ] #114
   - [x] #111    

### Items Carried Forward
- [ ]

### Notes
- Focus groups will be the platform to test out all different plans
- Jyoti and Alicia will review the addition of the system impacted youth as SMEs
- Have some sample ideas ready for the focus group regarding the 7 sections will be divided between participants
- System impacted youth will not participate in the first focus group
- Focus group will be held remotely (if results are not satisfactory, we may go in person)
- Size of focus group: 6 (but book double)
- Dot vote or card sort?
- Icebreakers: keep them easy (provide questions prior to the focus group)
- Is there a criteria for sending the participants to a breakout room? yes, will be predetermined by industry type or personality type or another, RP003 will provide more insight
- Sandy will incorporate infinity mapping 
- If this becomes larger, we will have facilitators in each room

### Tasks items from meeting
- Remind Bonnie to access 
  - BoP card sort
  - Video of the affinity mapping utilization that was presented to Super by Design
- Check Prioritized Backlog to queue for new UX researchers

**Comment by Rabia2219** [comment]
### Date: 2022-11-14

### Roll Call 
- [x] Bonnie
- [ ] Rabia
- [x] Megan
- [x] Taylor
- [x] Leroy
- [x] Sandy
- [x] Richard

### New Agenda Items
- [x] Quick 'hellos' for UX researchers who will be observing today (Trang, Rong, Faezeh, Aparna, Eva)
- [ ] Review
   - [ ] #111    
   - [ ] Onboard Richard #71 
   - [ ] Run through [creating a research form ](https://github.com/hackforla/YouthJusticeNav/issues/89#issuecomment-1312276119) to get feedback and adjust accordingly

### Items Carried Forward
- [ ]

### Notes

### Tasks items from meeting

**Comment by ExperimentsInHonesty** [comment]
Rong & Aparna- Observing
Trang, Faezeh, eva joining
