### ISSUE TITLE
YJN: Stakeholder Meeting Agenda

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/YouthJusticeNav#70]
### Overview
We need to keep track of our agenda for the biweekly stakeholder meeting.

### Action Items
- [ ] Create new agenda each week in comments
- [ ] Link comment here under resources
- [ ] Update slide deck with agenda
- [ ] Email the agenda as a link to the stakeholders on Tuesdays before 1 pm PDT

### Resources/Instructions
- [Template for agenda ](https://docs.google.com/presentation/d/1ePZ5qL9aMndKq2T6SBPVLGaTf1bHzkNvkv50_CL4IoQ/edit#slide=id.gfaa841ff41_0_8)
- [Example of tdm-calculator stakeholder agenda](https://github.com/hackforla/tdm-calculator/issues/888)

### Agenda by date
[2022-09-30](https://github.com/hackforla/YouthJusticeNav/issues/70#issuecomment-1262922776
)
[2022-11-18](https://github.com/hackforla/YouthJusticeNav/issues/70#issuecomment-1320240724)

**Comment by Rabia2219** [comment]
## 2022-05-27

### Notes:

- Write a paragraph for Alicia to present so she can have a summer intern join our project
- Create vdos for the difficult topics in the 7 legal areas in the FigJam session
   - Roger, Edin, Leah and Noella will take this on 
- Leah is our connection to Homeboy Industries
- Jyoti suggests that not all the material will be able to be translated and completely understandable by ALL community members (as suggested by Edin) and asks to pick maybe 10 areas
- Jyoti asked about the press release. We asked to get back at the next stakeholder meeting
  - They are not sure what to include in the press release yet
- Jyoti also asked if this 1 month includes the fundraising but it doesn't
- The stakeholders need send us their updated bios

**Comment by Rabia2219** [comment]
[Drive where documents related to the 7 areas are](https://drive.google.com/drive/u/2/folders/1Pmsm2Wg0C7uQeaDSMzd0JKSkzCQFPx2i)

**Comment by Rabia2219** [comment]
### Date: 2022-06-24

### Roll Call

- [ ] Bonnie
- [ ] Rabia
- [ ] Leroy
- [ ] Wendy
- [ ] Chali
- [ ] Megan
- [ ] Taylor

### New Agenda Items
- Feedback from stakeholders after document clean up from their end
- Feedback on the [7 topic areas](https://www.figma.com/file/65dhggLR6ik7CjoVEmFLKI/Youth-Justice-Nav-Designs?node-id=5%3A3)
- Review #72 


### Items Carried Forward



### Notes

### Tasks
- [ ]

**Comment by Rabia2219** [comment]
https://github.com/hackforla/tdm-calculator/issues/888

**Comment by Rabia2219** [comment]
Agenda for meeting

How has the scope changed

Proposal to hire a Project/Product Manager to develop a defined budget for Youth Justice Navigator Collabathon and Website building operations with the existing volunteer Product Manager and Agile Coach.

Scope of Work details
Project Management: Developing volunteer engagement roadmap and vendor management
Product Management: Developing Budget, funding proposal and presentation
Collabathon: Developing Collabathon roadmap and delivery plan
Website: Preparing 4-6 month roadmap for website development and 12 month goal setting

What happened Flom grant?
We will be reorganizing the information on the website so that there is space for the target audience and an about section for people who want to know more the people and details behind it
stakeholder to determine legal information navigation architecture 
Did they make progress on [YJN: Google Drive Audit](https://docs.google.com/spreadsheets/d/1QmUlCivtBkEicOL4MLegnn4NwmdhU3D6aur3exNfF44/)

What we are working on is 
Defining all the plans and work that needs to be conducted (review today).  
Prioritize plan and work
Diving into the work.

TDM issue for stakeholder deck example https://github.com/hackforla/tdm-calculator/issues/888

**Comment by Rabia2219** [comment]
Notes:
- we need to update the youthjusticnav.org site to reflect that it is the team site and add a link to youthjusticnavigator.org
- Roger and youth are making progress and almost done with section 1
- it would be ok to brand the tiktok videos

**Comment by Rabia2219** [comment]
[Agenda 2022-08-19](https://docs.google.com/presentation/d/1-n_O63Z9iD1Y0cPmufyy2IwwWYMcWQRCPh4xba_IsIY/edit?usp=sharing)

Roll Call:

- [ ] Bonnie
- [ ] Rabia
- [ ] Jyoti
- [ ] Alicia
- [ ] Roger

Notes:
- Send Bio specifications to Jyoti, Alicia and Roger
- Doreen will take over on updating the 7 section documentation
- Question from Jyoti: who will be hiring the new designer?
- Dana attended and would like to meet with Bonnie
- Rabia: we need to start thinking about the alignment interviews

**Comment by Rabia2219** [comment]
Add to agenda for Friday
https://www.figma.com/file/65dhggLR6ik7CjoVEmFLKI/Youth-Justice-Nav-Designs?node-id=5%3A4

**Comment by Rabia2219** [comment]
### Date: 2022-09-02

### Roll Call

- [ ] Bonnie
- [ ] Rabia
- [ ] Alicia
- [ ] Jyoti
- [ ] Roger
- [ ] Doreen

### New Agenda Items
- [Agenda 2022-09-02](https://docs.google.com/presentation/d/1HLWyqhz1cWpuBQZ88l3sXOMf_Ht7PSyIQmdHIfr_a6M/edit#slide=id.gfaa841ff41_0_8)

### Items Carried Forward

### Notes

### Tasks
- [ ]

**Comment by Rabia2219** [comment]
### Date: 2022-09-13

### Roll Call

- [x] Bonnie
- [x] Rabia
- [x] Alicia
- [x] Jyoti


### New Agenda Items

- [x] New FigJam Activity (Preference Matrix
- [x] Proposal: Bonnie to lead the youth in brainstorming sessions
- [x] Budget
   - [x] Allocation for Bonnie's hours
- [x] Scope creep on the original SoW for Rabia
- [x] Research Roadmaps
- [x] Jyoti's resource share


### Items Carried Forward

### Notes
- Meeting on the 16th to be cancelled
- Jyoti will set up a meeting with Karen regarding the video content website
- Bonnie to lead the youth in content creation ideation
- Possibility of in person Collabathon

### Tasks

- [x] Cancel meeting on September 16th
- [x] Remove non active members from forwarding
- [ ] Create updated SoW draft
- [ ] Emails:
   - [x] Brief email about cancellation and when to expect follow up emails and meeting notes
   - [ ] Meeting notes
   - [ ] Rabia's SoW options to Jyoti and Alicia
   - [x] Coordination with Roger
   - [x] Task items for Doreen

**Comment by Rabia2219** [comment]
### Email Drafts
#### Doreen

Hi Doreen, 

Hope you are doing well.

Alicia informed us that you would be returning as an active intern on the project and will continue where Mariana left off. We were hoping to talk to you directly at the September 2nd meeting so that we could convey our ask clearly, and this email in lieu.

There's two major asks:

1. Please review the [final changes](https://drive.google.com/drive/folders/15_08TquN7Dw_t3XAwB4LBFjbXEewItai?usp=sharing) that Mariana made to two (Section 1 and Section 4) of the seven sections.
  1.1 Please indicate the final sections in the [FigJam Ideation](https://www.figma.com/file/HdUm3eSnHcMIifAZYePvOX/Ideas-for-Collabathon-projects?node-id=0%3A1) by leaving a comment on a sticky note next to Section1 and 4 respectively.

2. Please review the [FigJam Ideation](https://www.figma.com/file/HdUm3eSnHcMIifAZYePvOX/Ideas-for-Collabathon-projects?node-id=0%3A1) and indicate terms that are already in the [Glossary](https://www.youthjusticenavigator.org/glossary) by placing a STAR next to the term.

Our next stakeholder meeting is on September 30th and we hope to get an update from you then. In the meantime, please do not hesitate to reach out via email if you have any questions or concerns.

Best,

Rabia

#### Roger 
Hi Roger,

Hope you are doing well. 

We missed you at the last meeting and would like to bring you up to speed with the new developments.

After a discussion with Alicia and Jyoti, it has been decided that I will be coordinating with you and the youth directly to set up training/work along sessions to complete the FigJam Ideation exercise. I will also work on creating some supplementary exercises to include along with the main exercise. 

What is a good day/time for you to meet with me for an initial discussion?

Best,

Bonnie

**Comment by Rabia2219** [comment]
Hi Roger,

Hope you are doing well. 

We missed you at the last meeting and would like to bring you up to speed. 

After a discussion with Alicia and Jyoti, it has been decided that I will be coordinating with you and the youth directly to set up training/work along sessions to complete the FigJam Ideation exercise. I will also work on creating some supplementary exercises to include along with the main exercise. 

What is a good day/time for you to meet with me for an initial discussion?

Best,

Bonnie

**Comment by Rabia2219** [comment]
### Meeting with Karen from Calamari Productions
#### Notes
- 9 times out of 10 people do not understand what's going on in the system
- 10 times out of 10 having a good lawyer makes the difference
- the videos that are used by Calamari are real life
- the content is used for training and education 
  - rarely on TV
- when a show airs, they do Facebook live
- they have a YouTube channel
- they have thought about adding commentary to the videos
  - will be open to us adding the commentary or turning them into games, etc through the Collabathon
- have provided pro bono content
- looking for funding
  - ready to leverage their success for BIG funding
- created the subscription site as a test
 - it is powered by an outsourced tech platform
 - gave out free subscription codes to a select group
 - intent is to keep it open source, don't want to make money through it
 - want to partner with a university for this
   - to run it
   - fund it
- 2 reasons for not putting this content on YouTube
  - people cannot access YouTube
  - professors don't like the ads
  - can't download the videos
    - mostly to crop and use as educational material
 - making this open source is a passion project now
- it is 'super easy' for her to let us know what video would go with each section on our site
- Jyoti wants to start funding
- What can HackforLA do to get this content on the site?
 - Karen would like some time to think and will get back to us
- we would like to use one of the videos for the Collabathon kit
- what is the ideal length of a video for educational purposes?
  - 10 minutes is the sweet spot
- they can provide videos, funding is needed to make them available and sustainable for various platforms
- tagging is needed
  - HackforLA can send some researcher to universities and educators to find out what kind of tags they would like
- they are just viewer description advisory at the beginning of the videos and YouTube setting for 18+
- Karen will get back to us

**Comment by Rabia2219** [comment]
### Date: 2022-09-30

### Roll Call

- [ ] Bonnie
- [x] Rabia
- [ ] Leroy
- [ ] Alicia
- [ ] Jyoti
- [x] Roger
- [x] Doreen
- [ ] Blake

### New Agenda Items
- [Agenda 2022-09-30](https://docs.google.com/presentation/d/1i6d2OXpnKMi6Rm6OPyhx88loMghYMtzO8eZ4cHpwAZg/edit)


### Items Carried Forward

### Notes 
- Doreen will review and update the drive audit spreadsheet
- Doreen will review the section numbering
- Roger will send his availability

### New tasks Items from meeting
- [ ]

**Comment by Rabia2219** [comment]
### Meeting with Roger

**Comment by Rabia2219** [comment]
### Date: 2022-10-14

### Roll Call

- [x] Bonnie
- [x] Rabia
- [x] Leroy
- [x] Alicia
- [x] Jyoti
- [x] Roger
- [ ] Doreen
- [ ] Blake

### New Agenda Items
- [Agenda 2022-10-14](https://docs.google.com/presentation/d/1KqvTnnFmWyRU8LXzna57XaWhAC10laNM_5brarxoqJY/edit)


### Items Carried Forward

### Notes 
- Doreen wasn't there but Section 1.5 has been removed, 1.0 no longer has a description and the Changes doc needs to reflect that
- Roger will send his pic today
- Jyoti is ok with moving forward with Calamari Productions but concerned about the PG ratings of the videos
- We will send a set of expectations (timeline and review process) to Calamari
- Alicia and Jyoti are of the opinion that the Board Members do not need to be involved too much in the survey process
- Alicia will reach out to Doreen to see if the sections can be broken down further for representation on the website
- Doreen will update the Numbered Files to add the rest of the section
- Set up meeting structure where everyone can work on section breakdown for information architecture
- Meeting with Roger: Wednesday Oct 19th 12pm to 3pm
- Jyoti wants a timeline for the Collabathon, whether it will be in person or virtual
- Jyoti/Alicia will provide their block out dates
- Jyoti sent documents for us to review

### New tasks Items from meeting
- [ ] Create a set of expectations for Calamari

**Comment by Rabia2219** [comment]
### Date: 2022-11-18

### Roll Call

- [x] Bonnie
- [x] Rabia
- [x] Leroy
- [x] Royston
- [ ] Alicia
- [ ] Jyoti
- [ ] Roger
- [x] Doreen
- [x] Blake

### New Agenda Items
- [Agenda 2022-11-18](https://docs.google.com/presentation/d/1exVOPrb2ueUNUqco9Vji5C0AnI38YvlBLQchPcy0elQ/edit)


### Items Carried Forward
### Notes 
- [Website Navigation Plan](https://docs.google.com/document/d/1DpSDKnDjq1OyEFDdTZWOyNRMhWKIpjnMFre6XDr864M/edit
) 
Doreen should be working on this document **in suggestion mode** in order to allow the YJN team to reflect the correct sections on the info architecture
### New tasks Items from meeting
