### ISSUE TITLE
YJN: Wiki: Research Plans

### ISSUE THREAD

**Issue by tbrogers6** [hackforla/YouthJusticeNav#74]
### Overview
We need to add all information for research plans to the wiki, so that we have one place to manage all of them

### Action Items
- [x] Create Issues
  - [x] Taylor
     - #76 
     - #77
     - #78 
    - #79
  - [x] Megan
     - #80 
     - #81 
     - #82
- [x] Customize Issues with only the checkboxes from this list that need to be done for each research issue

```
### Overview
We need to create an epic issue for Research Plan ___, so that we can have a running list of what is still needed.

### Action Items
- [ ] Copy the template into this issue
- [ ] Review spreadsheet to determine needed elements of epic (deleting anything that is not needed)
- [ ] Add any additional context required, short of writing a research plan into this issue.
- [ ] Create label
   - [ ] Add label to issue
   - [ ] Add link to issues with the label to the resources section
- [ ] Create wiki page
  - [ ] link it to resources below
  - [ ] link to Research Output page
  - [ ] add link to all issues with the label 
  - [ ] Fill out the information in the wiki
- [ ] Create folder to YJN Google Drive under UI/UX>Research with the name as the wiki page title
  - [ ] Add link to resources below
- [ ] Create issues (all may not be applicable)
  - [ ] Research Plan (internal)
  - [ ] Timeline
  - [ ] Forms/Survey/Script
  - [ ] emails text (if required)
  - [ ] recruitment plan (if required)
  - [ ] identification of recruitment channels
  - [ ] messaging for each type of channel
  - [ ] interest forms
  - [ ] selection criteria
  - [ ] Consent Plan
  - [ ] Research Plan (external) - this is a subset of the internal
  - [ ] Consent Form
  - [ ] Interviews
  - [ ] Synthesize interview findings (affinity mapping)
  - [ ] Competitive and comparison analysis
  - [ ] Persona, scenario, problem statement
  - [ ] Customer journey map
  - [ ] Feature prioritization
  - [ ] Usability test prototype
  - [ ] Synthesize usability test results

### Resources/Instructions

#### generic links for all research epics
- [Wiki page, Research Output](https://github.com/hackforla/YouthJusticeNav/wiki/Research-Output-Overview)
- [YJN Google Drive UI/UX, Research](https://drive.google.com/drive/u/0/folders/1BU4S1kASBX8PXr5nuTXANGS_1AtK_sdX)

#### Links for this specific epic
- Budget
  - [RP001 Time and Cost Budget]()
- WIKI
  - [Wiki page]()
- Issues
  - [All issues related to this Research Epic]()
- Google Drive
   - [RP___: ]()


```

### Resources/Instructions
- [Research Output Overview](https://github.com/hackforla/YouthJusticeNav/wiki/Research-Output-Overview)
- [Research Plan overview](https://github.com/hackforla/product-management/wiki/Research-Plan-Execution)

**Comment by ExperimentsInHonesty** [comment]
We updated the template today, and the related wiki pages.

There are still a few things to add to each issue
- Reformat the resources section
- Add the tasks 
```
- [ ] Create folder to YJN Google Drive under UI/UX>Research with the name as the wiki page title
  - [ ] Add link to resources below
```

**Comment by tbrogers6** [comment]
Got it, I've made the updates.

**Comment by Rabia2219** [comment]
@tbrogers6 @mmdrohan 
I've updated the - [ ] Create issues (all may not be applicable) part in the template above. Could you please update all the research  plan issues to reflect that? Thanks!

**Comment by Rabia2219** [comment]
There is no mention of a roadmap in this epic. We need to revisit this and add it to the CREATE ISSUES section, and then add to all the research plan epics. Plus, work on creating a template for it.
