### ISSUE TITLE
Time Card - Rabia

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/YouthJusticeNav#75]
### Overview
This issue tracks Rabia's hours worked per week.

### Action Items
- [ ] Create a new comment for each new week
- [ ] Add daily hours worked
- [ ] Add total hours worked for the week
- [ ] For each week, indicate whether
    - invoice was submitted
    - check was received
- [ ] Update total hours (worked, remaining) in resources below

### Resources/Instructions
- Total hours
   - Funded: 125
   - As of 2022-11-18
     - Worked: 119 hours, 30 minutes
     - Remaining: 5 hours, 30 minutes
   - As of 2023-01-29
     -  Worked: 125 hours, 30 minutes
     - Remaining: 0 hours
     - Over by: 30 minutes

**Comment by Rabia2219** [comment]
**Check Received**
- Tuesday, July 12: 9:15 am to 11:00 am (CDT) - Flom Grant
- Wednesday, July 13: 9:15 am to 11:00 am (CDT) - Flom Grant
- Wednesday, July 13: 2:00 pm to 02:45 pm (CDT) - Flom Grant
- Wednesday, July 13: 3:45 pm to 06:00 pm (CDT) - Flom Grant
- Wednesday, July 13: 7:00 pm to 09:00 pm (CDT) - Flom Grant

**Check Received**
- Monday, July 18th - 6:00 pm to 7:00 pm (CDT)
- Tuesday, July 19th - 1:00 pm to 2:00 pm (CDT)
- Wednesday, July 20th - 3:00 pm to 4:30 pm (CDT)
- Wednesday, July 20th - 7:15 pm to 8:15 pm (CDT)
- Thursday, July 21st - 8:00 am to 9:00 am (CDT)
- Thursday, July 21st - 1:30 pm to 2:30 pm (CDT)
- Thursday, July 21st - 6:30 pm to 8:00 pm (CDT)
- Friday July 22nd - 3:00 pm to 6:00 pm (CDT)

Total Hours = 21 (July 12th - July 22nd)

**Comment by Rabia2219** [comment]
- [x] Invoice submitted
- [x] Check received

Monday Aug 8th - 12:30 pm to 1:30 pm (CDT) Planning with Bonnie
Monday Aug 8th - 6:00 pm to 6:30 pm (CDT) Team meeting
Tuesday Aug 9th - 12:00 pm to 12:30 pm (CDT) Planning with Bonnie
Wednesday Aug 10th - 5:30 pm to 8:30 pm (CDT) Template issues
Thursday Aug 11th - 3:15 pm to 4:30 pm (CDT) Template issues
Thursday Aug 11th - 5:00 pm to 9:00 pm (CDT) Template issues
Friday Aug 12th - 12:00 pm to 2:00 pm (CDT) Template issues
Friday Aug 12th - 3:15 pm to 7:15 pm (CDT) Template issues, team meeting, meeting with Bonnie
Monday Aug 15th 3:00 pm to 5:00 pm (CDT) Template issues
Monday Aug 15th 6:00 pm to 6:30 pm (CDT) Team meeting
Tuesday Aug 16th 4:00 pm - 6:00 pm (CDT) Template issues
Wednesday Aug 17th 9:00 am to 10:30 am (CDT) Template issues, agenda creation
Friday Aug 19th 5:00 pm to 6:30 pm (CDT) Stakeholder meeting, meeting with Dana, removing her email from fwding
Total Hours = 22 hours, 45 minutes

**Comment by Rabia2219** [comment]
Monday Aug 22nd - 5:30 pm to 7:00 pm (CDT) template issues, team meeting, email

**Comment by Rabia2219** [comment]
#### Week of Aug 29th - Sept 2nd
Monday Aug 29th - 12:30 pm to 1:30 pm (CDT) website template
Monday Aug 29th - 5:00 pm to 5:30 pm (CDT) Wiki update (roadmap), roadmap template issues
Monday Aug 29th - 6:00 pm to 7:45 pm (CDT) team meeting, Wiki update

Total Hours = 

- [ ] Invoice submitted
- [ ] Check received

**Comment by Rabia2219** [comment]
#### Week of Sept 12th - Sept 16th
Monday Sep 12th 6 pm - 7 pm (CDT) Team Meeting
Tuesday Sep 13th 12 pm - 1 pm (CDT) Preference Matrix
Tuesday Sep 13th 6 pm - 7 pm (CDT) Ad hoc with Alicia & Jyoti
Wednesday Sep 14th 12:30 pm - 1:30 pm (CDT) follow up email, meeting notes, update email fwding, calendaring 

Total Hours: 4 hours

- [x]  Invoice submitted
- [ ]  Check received

**Comment by Rabia2219** [comment]
#### Week of Sept 19th - Sept 25th

Monday Sep 19th 6 pm - 7 pm (CDT) Team Meeting 
Tuesday Sep 20th 10:45 am - 11:45 am (CDT) Research Plan Template
Tuesday Sep 20th 6:45 pm - 7:15 pm (CDT) Internal Research Plan Issues (30)
Wednesday Sep 21st 10:45 pm - 12:15 pm (CDT) (90) letter template
Wednesday Sep 21st 1:00 pm - 1:30 pm (CDT) (30) email correspondence with Roger, Karen/Jyoti
Thursday Sep 22nd 12 pm - 1:30 pm (CDT) (90) draft for Doreen, Karen
Thursday Sep 22nd 5 pm - 7:15 pm (CDT) (135) meeting with Karen
Friday Sep 23rd 3:00 pm - 4:15 pm (CDT) (75) FigJam cleanup
Friday Sep 23rd 6:30 pm - 8:00 pm (CDT) (90) Team meeting


Total Hours: 11 hours

- [x]  Invoice submitted
- [x]  Check received

**Comment by Rabia2219** [comment]
#### Week of Sept 26th - Oct 2nd

Monday Sept 26th 12:30 pm - 1:30 pm (CDT) meeting setup/email (Roger), document setup/email (Doreen), slack messaging team members
Thursday Sept 28th 8 am - 9:30 am (CDT) Zoom meeting setup, Google calendar invites, email to Roger, drive organization
Thursday Sept 28th 5:30 pm - 7:30 pm (CDT) new SoW, Stakeholder meeting agenda, wiki update, PM meeting agenda issue
Friday Sept 30th 9:30 am - 10:00 am (CDT) research plan review


Total Hours: 5 hours,

- [x]  Invoice submitted
- [x]  Check received

**Comment by Rabia2219** [comment]
#### Week of Oct 3rd  - Oct 9th

Monday Oct 3rd 6 pm - 7 pm (CDT) Team meeting
Friday Oct 7th  4:30 pm - 5:30 pm (CDT) team meeting, email and slack msgs, agenda, template update


Total Hours: 2 hours

- [x]  Invoice submitted
- [x]  Check received

**Comment by Rabia2219** [comment]
#### Week of Oct 10th  - Oct 16th

Friday Oct 14th 3:00 pm - 6:30 pm (CDT) agenda creation, Stakeholder meeting, emails, slack msging

Total Hours: 3 hours, 30 minutes

- [x]  Invoice submitted
- [x]  Check received

**Comment by Rabia2219** [comment]
#### Week of Oct 17th  - Oct 23rd

Monday Oct 17th 6 pm - 7 pm (CDT) Team meeting
Friday Oct 21st  4:30 pm - 5:30 pm (CDT) team meeting, meeting invites, slack msging

Total Hours: 2 hours

- [x]  Invoice submitted
- [x]  Check received

**Comment by Rabia2219** [comment]
#### Week of Oct 24th  - Oct 30th

Monday Oct 24th  11:30 am - 12:00 pm (CDT) slack msging, email
Monday Oct 24th 6 pm - 7 pm (CDT) Team meeting
Tuesday Oct 25th 9:30 am - 10:30 am (CDT) emails
Wednesday Oct 26th 11 am - 1:00 pm (CDT) SoW, roadmaps
Thursday Oct 27th 11:00 am - 1:00 pm (CDT) SoW, roadmaps
Friday Oct 28th 1:45 pm - 2:15 pm (CDT) replies to Sandy, Royston email
Total Hours:  7 hours, minutes

- [x]  Invoice submitted
- [x]  Check received

**Comment by Rabia2219** [comment]
#### Week of Oct 31st  - Nov 6th

Monday Oct 31st 6 pm - 7 pm (CDT) Team meeting, agenda, issue review, slack msging with UX researhers
Tuesday
Wednesday
Thursday
Friday Nov 4th 6 pm - 7:30 pm Youth session, PM meeting, calendar invites
Total Hours:  2 hours, 30 minutes

- [x]  Invoice submitted
- [x]  Check received

**Comment by Rabia2219** [comment]
#### Week of Nov7th  - Nov 13th

Monday Nov 7th 6 pm - 7 pm (CDT) Team meeting, agenda
Tuesday
Wednesday
Thursday
Friday Nov 11th 5pm - 7 pm (CDT) Meeting with Bonnie: worked on research templates

Total Hours:  3 hours, minutes

- [x]  Invoice submitted
- [x]  Check received

**Comment by Rabia2219** [comment]
Week of Nov14th - Nov 20th

Monday Nov 14th 12:00 pm - 1:30 pm (CDT) research templates, forms, meeting agenda
Tuesday
Wednesday
Thursday
Friday Nov 18th 8:30 am - 9:00 am (CDT) 
Friday Nov 18th 10:00 am - 1:30 pm (CDT)
Friday Nov 18th 6:00 pm - 7:30 pm (CDT)


Total Hours:  7 hours,  minutes

- [x] Invoice submitted
- [x]  Check received

**Comment by ExperimentsInHonesty** [comment]
@Rabia2219 please remember to update your hours since Nov for  YJN

**Comment by ExperimentsInHonesty** [comment]
also sent message to Rabia on slack.

**Comment by Rabia2219** [comment]
Week of 2023-01-16 through 2023-01-22

Total Hours:  2 hours,  30 minutes

- [x] Invoice submitted
- [ ]  Check received

**Comment by Rabia2219** [comment]
Week of 2023-01-23 through 2023-01-29


Total Hours:  3 hours,  30 minutes

- [x] Invoice submitted
- [ ]  Check received
