### ISSUE TITLE
Research Plan 5: End of Day Surveys

### ISSUE THREAD

**Issue by mmdrohan** [hackforla/YouthJusticeNav#80]
### Overview
We need to create an epic issue for Research Plan 005, so that we can have a running list of what is still needed.

### Action Items
- [x] Copy the template into this issue
- [x] Review spreadsheet to determine needed elements of epic (deleting anything that is not needed)
- [x] Add any additional context required, short of writing a research plan into this issue.
- [x] Create label
   - [x] Add label to issue
   - [x] Add link to issues with the label to the resources section
- [x] Create folder to YJN Google Drive under UI/UX>Research with the name  as the wiki page title
  - [x] Add link to resources below
- [x] Create wiki page
  - [x] link it to resources below
  - [x] link to Research Output page
  - [x] add link to all issues with the label 
  - [x] Fill out the information in the wiki
- [x] Transfer to product
   - [x] Add product label
   - [x] Put in prioritized backlog
   - [x] Unassign yourself
- [x] Create issues
  - [x] Research Plan (internal)
  - [ ] Timeline
  - [ ] Forms/Survey/Script
  - [ ] emails text (if required)
  - [ ] recruitment plan (if required)
  - [ ] identification of recruitment channels
  - [ ] messaging for each type of channel
  - [ ] interest forms
  - [ ] selection criteria
  - [ ] Consent Plan
  - [ ] Research Plan (external) - this is a subset of the internal
  - [ ] Consent Form
  - [ ] Interviews
  - [ ] Synthesize interview findings (affinity mapping)
  - [ ] Competitive and comparison analysis
  - [ ] Persona, scenario, problem statement
  - [ ] Customer journey map
  - [ ] Feature prioritization
  - [ ] Usability test prototype
  - [ ] Synthesize usability test results

#### generic links for all research epics
- [Wiki page, Research Output](https://github.com/hackforla/YouthJusticeNav/wiki/Research-Output-Overview)
- [YJN Google Drive UI/UX, Research](https://drive.google.com/drive/u/0/folders/1BU4S1kASBX8PXr5nuTXANGS_1AtK_sdX)

#### Links for this specific epic
- Budget
  - [RP005 Time and Cost Budget](https://docs.google.com/spreadsheets/d/1Fc9d3_Cxeo8BG_GEyxB_pdvrSVVgU1C5VLIz6ErRYCQ/edit#gid=1519939665)
- WIKI
  - [Wiki page](https://github.com/hackforla/YouthJusticeNav/wiki/RP005:-End-of-Day-Surveys)
- Issues
  - [All issues related to this Research Epic](https://github.com/hackforla/YouthJusticeNav/labels/Research%3A%20RP005)
- Google Drive
   - [RP005: End of Day Surveys google drive](https://drive.google.com/drive/folders/1VDZoRnoHYkdgal6dtyBEeTV-t1QP6EYx?usp=sharing)

**Comment by tbrogers6** [comment]
I'm not sure if the last 4-5 items are relevant the project. They are on the timeline template but not on the list of tasks found on the time and cost budget google sheet.

Email text is on here but not on the budget google sheet. I also added a for the survey data analysis, which I believe should be on the timeline template and the budget sheet. @ExperimentsInHonesty @Rabia2219
