### ISSUE TITLE
Create template issues for all research plan epics

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/YouthJusticeNav#83]
### Overview
We need to create template issues for all the research plan epics so that it is easier to create those issues for each of the research plans.

### Action Items

- [ ] Determine what needs to be in each template
- [ ] Review
- [ ] Create template issues for the following
  - [ ] Research Plan for Internal Use
  - [ ] Research Plan Timeline
  - [ ] Research Plan Forms/Survey/Script
  - [ ] emails text (if required)
  - [ ] Research Plan Recruitment
      - [ ] Identification of recruitment channels
      - [ ] Messaging for each type of channel
      - [ ] Interest forms
  - [ ] Selection Criteria
  - [ ] Consent Plan
     - [ ] Consent Form
  - [ ] External Research Plan
 
### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by ExperimentsInHonesty** [comment]
Research Plans
- #76
- #77 
- #78 
- #79 
- #80 
- #81 
- #82 
- #96
