### ISSUE TITLE
YJN: Research Roadmap Collabathon

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/YouthJusticeNav#94]
### Overview
We need to create a research roadmap for Collabathon

#### Details
Each Research Plan fits into a Research Roadmap (e.g. If we are creating multiple research plans for the Collababthon, then the Research Roadmap document is where we decide what all the plans are and general overview.  Details are left for the Individual Research Plans).

### Action Items
- [x] replace all references in this issue to [name of type] with the name of the type
- [x] Add the milestone: `Research Roadmap Create Wiki Page` to this issue
- [x] Create a new page on the wiki for the roadmap called: `Research: Collabathon` using the template for Research Roadmap
  - [x] link it to the Research Output Overview wiki page
- [x] Change milestone: `Research Roadmap Document Creation`
  - [x] Put back in Prioritized Backlog under the new milestone
- [x] Go to the Google Drive, Research, 1. Research by Type, Folder
   - [x] Create a new folder in the drive called Collabathon
- [x] Make a new document using the Research Roadmap report template 
  - [x] Move your document from "My Drive" to the shared drive YJN folder that you just created.
- [x] Name your document to be called YJN: Research Roadmap: Collabathon
- [x] Add link to the research roadmap document in resources below
- [x] Update the Table of contents (page 2) when you are finished with document

### Resources/Instructions
- [YJN: WIKI template: Research Roadmap](https://github.com/hackforla/YouthJusticeNav/wiki/research-roadmap-wiki-template)
- [YJN: Wiki: Research Output Overview](https://github.com/hackforla/YouthJusticeNav/wiki/Research-Output-Overview)
- [YJN: Google Drive folder: 1. Research by Type Folder](https://drive.google.com/drive/folders/1duz_aeeDNtozbDSrDsZ8tl6tLLBHmcge?usp=sharing)
- [YJN: Document template: Research Roadmap](https://docs.google.com/document/d/1rIq_s2ggjDfPuGhFP_fjoY2SnWzzEoipNZ7RrqITpcY/template/preview)
- [YJN: Research Roadmap: Collabathon](https://docs.google.com/document/d/100jrAKq5BHxTpDC6EfVUZivEleppI9cbG9aGe7p-2oc/edit#)

### Collabathon Research Assets
- [Research Roadmap Wiki: Collabathon](https://github.com/hackforla/YouthJusticeNav/wiki/Research:-Collabathon)

**Comment by Rabia2219** [comment]
@tbrogers6 
This is the roadmap issue for you to work on...you can move it to 'In Progress' once you start working on it...I've customized the template for the Collabathon Research...it is the last link in the Resources/Instructions...
